FROM nginx:1.27-alpine

COPY frontend-student/index.html frontend-student/app.js frontend-student/styles.css \
  frontend-student/slides.css frontend-student/slideRenderer.js /usr/share/nginx/html/

EXPOSE 80
